services:
  # PostgreSQL Database
  postgres:
    image: postgres:17
    container_name: vgu_care_db
    environment:
      POSTGRES_DB: vgu_care
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - vgu_network

  # Backend API
  backend:
    build: ./backend
    container_name: vgu_care_api
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:123456@postgres:5432/vgu_care
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - vgu_network

  # Frontend React App
  frontend:
    build: ./frontend
    container_name: vgu_care_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    networks:
      - vgu_network

volumes:
  postgres_data:

networks:
  vgu_network:
    driver: bridge